CodeFirst/Models/Employee.cs
namespace CodeFirst.Models
{
    public class Employee
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }

        public double Salary { get; set; }
    }
}

CodeFirst/Models/ErrorViewModel.cs
namespace CodeFirst.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CodeFirst/Controllers/EmpController.cs
using CodeFirst.Data;
using CodeFirst.Models;
using Microsoft.AspNetCore.Mvc;

namespace CodeFirst.Controllers
{
    public class EmpController : Controller
    {
        private readonly ApplicationDbContext db;

        public EmpController(ApplicationDbContext db)
        {

            this.db = db;
        }
        public IActionResult Index()
        {
            var data = db.Emp.ToList();
            return View(data);
        }
        public IActionResult AddEmp()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddEmp(Employee e)

        {
            db.Emp.Add(e);
            db.SaveChanges();
            TempData["msg"] = "User Succefully Insert Data";
            return RedirectToAction("Index");
        }

        public IActionResult DeleteEmp(int id)
        {
            var d = db.Emp.Find(id);
            // var dd=db.Emp.Where(s=>s.Id==id).SingleOrDefault();

            if (d != null)
            {
                db.Emp.Remove(d);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {

                return RedirectToAction("Index");
            }

        }
        public IActionResult EditEmp(int id)
        {
            var d = db.Emp.Find(id);
            // var dd=db.Emp.Where(s=>s.Id==id).SingleOrDefault();
            return View(d);


        }
        [HttpPost]
        public IActionResult EditEmp(Employee e)
        {
            db.Emp.Update(e);
            db.SaveChanges();
            return RedirectToAction("Index");


        }
    }
}

CodeFirst/Controllers/HomeController.cs
using System.Diagnostics;
using CodeFirst.Models;
using Microsoft.AspNetCore.Mvc;

namespace CodeFirst.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CodeFirst/Views/Emp/AddEmp.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model Employee

<form method="post">
    <div class="form-group">
        Name
        <input type="text" asp-for="Name" name="Name" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
      </div>
    <div class="form-group">
        Email
        <input type="text" asp-for="Email" name="Email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
    </div>
            <div class="form-group">
                Salary
                <input type="text" asp-for="Salary" name="Salary" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
    </div>


                    <button type="submit" class="btn btn-primary">Submit</button>
</form>

CodeFirst/Views/Emp/EditEmp.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model Employee
<form method="post">
    <div class="form-group">
        Name
        <input type="text" asp-for="Name" name="Name" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
      </div>
    <div class="form-group">
        Email
        <input type="text" asp-for="Email" name="Email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
    </div>
            <div class="form-group">
                Salary
                <input type="text" asp-for="Salary" name="Salary" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
    </div>


                    <button type="submit" class="btn btn-primary">Save Changes</button>
</form>

CodeFirst/Views/Emp/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model List<Employee>
@if(TempData["msg"]!=null){

    @TempData["msg"]
}
<a  asp-controller="Emp" asp-action="AddEmp"> Add Emp</a>

<table class="table">
    <thead>
        <tr>
            <th scope="col">Id</th>
            <th scope="col">Name</th>
            <th scope="col">Email</th>
            <th scope="col">Salary</th>
            <th scope="col">Action</th>
            <th scope="col">Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var d in Model)
        {
            <tr>
                <th scope="row">@d.Id</th>
                <td>@d.Name</td>
                <td>@d.Email</td>
                <td>@d.Salary</td>
                <td><a class=" btn btn-sm btn-danger"  asp-action="DeleteEmp" asp-route-Id="@d.Id" onclick="return confirm('are u want to delete thie data') ">Delete</a></td>
                <td><a class=" btn btn-sm btn-warning" asp-action="EditEmp" asp-route-Id="@d.Id">Edit</a></td>
            </tr>
        }

CodeFirst/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CodeFirst/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CodeFirst</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CodeFirst.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CodeFirst</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - CodeFirst - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>